name: Setup and Build
description: Generic setup action
inputs:
  node-version:
    required: false
    type: string
    default: '20.18.0'
  run-build:
    required: false
    type: string
    default: 'false'
  node-options:
    required: false
    type: string
    default: '--max-old-space-size=4096'

runs:
  using: composite

  steps:
    - uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Set Node.js version to ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Build project
      if: ${{ inputs.run-build == 'true' }}
      shell: bash
      env:
        NODE_OPTIONS: ${{ inputs.node-options }}
      run: pnpm run build
